# Generated by Django 4.2 on 2026-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
