# Generated by Django 4.2 on 2026-08-27

from django.db import migrations, models
from django.db.models import Q


_CONVERTER = None


def _textile_to_markdown(source):
    """Copy of wiki.textile_to_markdown, inlined so this migration stays runnable
    after that module (and its one-time converter deps) are removed.

    Imports of `textile` and `markdownify` happen here, only when historical
    Textile rows actually need converting. Empty databases skip this function.
    """
    global _CONVERTER
    if _CONVERTER is not None:
        return _CONVERTER(source)

    """Convert Textile markup to Markdown via HTML."""

    import re

    import textile
    from markdownify import ATX, MarkdownConverter


    _GENERIC_CODE_CLASSES = frozenset({
        "highlight",
        "hll",
        "linenos",
        "footnote",
    })

    # Textile (and some wiki pages) invert block code as <code><pre>...</pre></code>.
    _INVERTED_CODE_PRE = re.compile(
        r"<code(\b[^>]*)>\s*<pre(\b[^>]*)>(.*?)</pre>\s*</code>",
        re.DOTALL | re.IGNORECASE,
    )

    # Block-level embeds/tables/scripts kept as raw HTML so markdownify cannot drop
    # them, and python-markdown treats them as HTML blocks rather than wrapping <p>.
    _BLOCK_RAW_TAGS = frozenset({
        "iframe",
        "object",
        "video",
        "audio",
        "table",
        "script",
        "style",
    })

    _LINE_WITH_CONTENT = re.compile(r"^(.*)", flags=re.MULTILINE)

    _ORDERED_IN_PARAGRAPH = re.compile(r"(?m)^(\d+)\. ")


    def _class_list(el):
        classes = el.get("class") or []
        if isinstance(classes, str):
            return classes.split()
        return list(classes)


    def _language_from_classes(classes):
        for cls in classes:
            if not cls or cls in _GENERIC_CODE_CLASSES:
                continue
            if cls.startswith("language-"):
                return cls[len("language-"):]
            return cls
        return ""


    def _code_language(el):
        """Language class on <pre>, nested <code>, or a wrapping <code>."""
        lang = _language_from_classes(_class_list(el))
        if lang:
            return lang
        if getattr(el, "name", None) != "code":
            code = el.find("code")
            if code is not None:
                lang = _language_from_classes(_class_list(code))
                if lang:
                    return lang
        parent = getattr(el, "parent", None)
        if parent is not None and getattr(parent, "name", None) == "code":
            return _language_from_classes(_class_list(parent))
        return ""


    def _normalize_inverted_code_pre(text):
        return _INVERTED_CODE_PRE.sub(r"<pre\2><code\1>\3</code></pre>", text)


    class _TextileMarkdownConverter(MarkdownConverter):
        """markdownify converter tuned for this wiki's Markdown renderer.

        Textile footnotes become <sup class="footnote"><a>N</a></sup> references
        and <p class="footnote"><sup>N</sup> def</p> definitions. markdownify would
        otherwise emit dangling [N](#fn-hash) links; emit Python-Markdown footnote
        syntax ([^N] / [^N]: def) so the footnotes extra can parse them.

        Block <pre> (and inverted <code><pre>) become fenced Markdown. Inline
        <code> from Textile @print()@ stays as backticks via markdownify.

        Embeds (iframe/object/embed/param/video/audio) and tables are kept as raw
        HTML because markdownify would drop players and turn tables into pipes
        that this wiki's renderer does not parse.
        """

        def _keep_raw_html(self, el, text, parent_tags):
            html = str(el)
            if parent_tags and "_inline" in parent_tags:
                return html
            if (el.name or "").lower() in _BLOCK_RAW_TAGS:
                return "\n\n%s\n\n" % html
            return html

        convert_iframe = _keep_raw_html
        convert_object = _keep_raw_html
        convert_embed = _keep_raw_html
        convert_param = _keep_raw_html
        convert_video = _keep_raw_html
        convert_audio = _keep_raw_html
        convert_source = _keep_raw_html
        convert_table = _keep_raw_html
        convert_style = _keep_raw_html

        def convert_script(self, el, text, parent_tags):
            # Keep src= embeds (gist, imgur, instagram, Brightcove, tinypay).
            # Drop inline scripts so conversion never copies executable bodies.
            if not (el.get("src") or "").strip():
                return ""
            return self._keep_raw_html(el, text, parent_tags)

        def convert_code(self, el, text, parent_tags):
            # Inverted <code><pre>: inner pre is already a fenced block.
            if el.find("pre") is not None:
                return text
            return super().convert_code(el, text, parent_tags)

        def convert_sup(self, el, text, parent_tags):
            if "footnote" in _class_list(el):
                anchor = el.find("a")
                num = (anchor.get_text() if anchor is not None else el.get_text())
                num = (num or "").strip()
                if num:
                    return "[^%s]" % num
            return super().convert_sup(el, text, parent_tags)

        def convert_p(self, el, text, parent_tags):
            if "footnote" in _class_list(el):
                sup = el.find("sup")
                num = (sup.get_text() if sup is not None else "").strip()
                body = (text or "").strip()
                if num and body.startswith(num):
                    body = body[len(num):].lstrip()
                if num:
                    return "\n\n[^%s]: %s\n\n" % (num, body)
            result = super().convert_p(el, text, parent_tags)
            # Textile often writes "1. foo" inside a <p>. python-markdown would
            # turn those lines into <ol>; escape the marker so they stay paragraphs.
            return _ORDERED_IN_PARAGRAPH.sub(r"\1\\. ", result)

        def convert_span(self, el, text, parent_tags):
            if parent_tags and "_noformat" in parent_tags:
                return text or ""
            if "caps" in _class_list(el):
                return '<span class="caps">%s</span>' % (text or "")
            return text or ""

        def convert_li(self, el, text, parent_tags):
            # python-markdown only nests lists indented by 4 spaces. markdownify's
            # default uses the bullet width (2 for "* ") and rotating +/- bullets,
            # which flattens Textile ** / ## nested lists.
            text = (text or "").strip()
            if not text:
                return "\n"

            parent = el.parent
            if parent is not None and parent.name == "ol":
                if parent.get("start") and str(parent.get("start")).isnumeric():
                    start = int(parent.get("start"))
                else:
                    start = 1
                bullet = "%s." % (start + len(el.find_previous_siblings("li")))
            else:
                bullet = "*"
            bullet = bullet + " "
            nested_indent = "    "

            def _indent_for_li(match):
                line_content = match.group(1)
                return nested_indent + line_content if line_content else ""

            text = _LINE_WITH_CONTENT.sub(_indent_for_li, text)
            text = bullet + text[len(nested_indent):]
            return "%s\n" % text


    def textile_to_markdown(source):
        """Return Markdown equivalent of a Textile string.

        Empty or None input yields an empty string. Headings, links, emphasis,
        lists, code, images, and blockquotes are preserved via textile -> HTML
        -> markdownify. Textile footnotes become Python-Markdown [^n] markers.
        Block code becomes fenced Markdown; inline @code@ becomes backticks.
        Embeds (iframe/object/embed) and tables are kept as raw HTML.
        """
        if not source:
            return ""
        source = _normalize_inverted_code_pre(source)
        html = textile.textile(source)
        html = _normalize_inverted_code_pre(html)
        markdown = _TextileMarkdownConverter(
            heading_style=ATX,
            code_language_callback=_code_language,
            bullets="*",
            keep_inline_images_in=["td", "th"],
        ).convert(html)
        return markdown.strip()
    _CONVERTER = textile_to_markdown
    return _CONVERTER(source)


def convert_textile_data(apps, schema_editor):
    """Fill empty Page.markdown from Textile Page.text; convert PageVersion.text.

    Schema ops after this drop Page.text (Textile) and rename Page.markdown -> text.
    """
    Page = apps.get_model("wiki", "Page")
    PageVersion = apps.get_model("wiki", "PageVersion")

    pages_to_fill = Page.objects.filter(Q(markdown__isnull=True) | Q(markdown=""))
    versions = PageVersion.objects.all()
    if not pages_to_fill.exists() and not versions.exists():
        return

    for page in pages_to_fill.iterator():
        source = page.text or ""
        if source.strip():
            try:
                page.markdown = _textile_to_markdown(source)
            except Exception:
                page.markdown = source
        else:
            page.markdown = source
        page.save(update_fields=["markdown"])

    for version in versions.iterator():
        source = version.text or ""
        if not source.strip():
            continue
        try:
            version.text = _textile_to_markdown(source)
        except Exception:
            # Textile can crash on a few historical pages; leave source as-is
            # (typically already HTML, which Markdown still renders).
            continue
        version.save(update_fields=["text"])


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0004_page_markdown"),
    ]

    operations = [
        migrations.RunPython(convert_textile_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="page",
            name="text",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="markdown",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="page",
            name="text",
            field=models.TextField(),
        ),
    ]
